language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

env:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1

# Clones WordPress and configures our testing environment.
before_script:
  # Setup Coveralls
  - phpenv local 5.5
  - composer install --no-interaction
  - phpenv local --unset

  - npm install

  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - grunt checktextdomain
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then vendor/bin/phpmd includes text codesize,naming,unusedcode; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then vendor/bin/phpcpd -n includes; fi
  - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml includes
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  # Push coverage off to Codecov
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
